server:
  port: 8081

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
        compression.type: snappy
        batch.size: 32768
        linger.ms: 5

logging:
  level:
    com.gov: DEBUG
    org.springframework.kafka: INFO
